"""sync models

Revision ID: 21684ca8ffd4
Revises: c06976e82a75
Create Date: 2026-01-19 10:47:59.443916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21684ca8ffd4'
down_revision: Union[str, Sequence[str], None] = 'c06976e82a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Add column as nullable
    op.add_column(
        'users',
        sa.Column('hashed_password', sa.String(), nullable=True)
    )

    # 2. Backfill existing users with a dummy hash
    op.execute(
        "UPDATE users SET hashed_password = 'TEMP_MIGRATION_HASH'"
    )

    # 3. Enforce NOT NULL
    op.alter_column(
        'users',
        'hashed_password',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
